ARG ROS_DISTRO="jazzy"
FROM ros:${ROS_DISTRO}

RUN apt update && apt upgrade -y && \
    apt install autoconf libtool -y
RUN mkdir ec_dev && cd ec_dev && \
    git clone https://gitlab.com/etherlab.org/ethercat.git && \
    cd ethercat && \
    git checkout stable-1.6 && \
    ./bootstrap && \
    ./configure --prefix=/usr/local/etherlab --disable-kernel && \
    make && make install

RUN mkdir /ros2_dev && cd /ros2_dev && \
    git clone https://github.com/ICube-Robotics/ethercat_driver_ros2.git && \
    cd ethercat_driver_ros2 && \
    git checkout jazzy && \
    . /opt/ros/${ROS_DISTRO}/setup.sh && \
    rosdep install --ignore-src --from-paths . -y -r && \
    colcon build --symlink-install --cmake-args -DBUILD_TESTING=OFF
