ARG ROS_DISTRO="jazzy"
FROM ecat_ros2_workshop:${ROS_DISTRO}

RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -qqy \
    dbus-x11 \
    mesa-utils \
    net-tools \
    novnc \
    onboard \
    tigervnc-standalone-server \
    tigervnc-xorg-extension \
    x11-apps \
    xfce4 \
    curl \
    dirmngr \
    software-properties-common \
    apt-transport-https \
    gnupg \
    wget \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir ~/.vnc \
 && echo "#!/bin/sh\nstartxfce4" > ~/.vnc/xstartup \
 && chmod +x ~/.vnc/xstartup

# Install VSCodium (Open Source build of VSCode)
RUN wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
  | gpg --dearmor \
  | sudo tee /usr/share/keyrings/vscodium-archive-keyring.gpg >/dev/null && \ 
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs vscodium main' \
  | sudo tee /etc/apt/sources.list.d/vscodium.list && \
    apt-get update && \
    apt-get install -y codium && \
    rm -rf /var/lib/apt/lists/*

# Install Chromium from Debian bookworm repository (avoid snap packages in Docker)

# Add Debian repo (bookworm)
RUN echo "deb [arch=amd64] http://deb.debian.org/debian bookworm main" >> /etc/apt/sources.list.d/debian.list && \
    wget -qO - https://ftp-master.debian.org/keys/archive-key-12.asc | apt-key add -

# Install Chromium from Debian
RUN apt-get update && \
    apt-get install -y --no-install-recommends chromium && \
    rm -rf /var/lib/apt/lists/*

# Optional: symlink for convenience
RUN ln -s /usr/bin/chromium /usr/bin/chromium-browser

COPY .docker/ros_entrypoint_novnc.sh /ros_entrypoint.sh
RUN chmod +x /ros_entrypoint.sh
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]